# Generated by Django 5.2.12 on 2026-05-26 11:02

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0002_symptomlog_treatmentphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_circle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareGiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(choices=[('son', 'Son'), ('daughter', 'Daughter'), ('spouse', 'Spouse / Partner'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('nurse', 'Nurse / Caregiver'), ('doctor', 'Doctor'), ('friend', 'Friend'), ('other', 'Other')], default='other', max_length=20)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregivers', to='care.carecircle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, help_text='e.g. 20 mg', max_length=100)),
                ('time_of_day', models.CharField(choices=[('morning', '🌅 Morning'), ('afternoon', '☀️ Afternoon'), ('evening', '🌆 Evening'), ('night', '🌙 Night (before bed)'), ('meal', '🍽 With meal')], default='morning', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_course', models.ForeignKey(blank=True, help_text='Optional link to a treatment course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_medications', to='treatments.treatmentcourse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time_of_day', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('feeling_score', models.PositiveSmallIntegerField(blank=True, help_text='Overall feeling 1–10', null=True)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, help_text='Pain level 0–10 (0 = no pain)', null=True)),
                ('sleep_score', models.PositiveSmallIntegerField(blank=True, help_text='Sleep quality 1–10', null=True)),
                ('mood', models.CharField(blank=True, choices=[('great', '😄 Great'), ('good', '🙂 Good'), ('okay', '😐 Okay'), ('low', '😔 Low'), ('bad', '😟 Bad')], max_length=10)),
                ('symptoms', models.TextField(blank=True, help_text='Any symptoms, concerns, or free notes')),
                ('medications_taken', models.BooleanField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('patient', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('taken', models.BooleanField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='care.medicationschedule')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('schedule', 'date')},
            },
        ),
    ]
