# Generated by Django 5.2.12 on 2026-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_painlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='escalationlog',
            new_name='care_escala_patient_81e60e_idx',
            old_name='care_escala_patient_date_idx',
        ),
        migrations.RenameIndex(
            model_name='escalationlog',
            new_name='care_escala_acknowl_a015a6_idx',
            old_name='care_escala_ack_token_idx',
        ),
        migrations.AlterField(
            model_name='painlog',
            name='severity',
            field=models.PositiveSmallIntegerField(help_text='1 (mild) – 10 (severe)'),
        ),
    ]
