# Generated by Django 5.2.12 on 2026-08-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0004_alter_aimodel_model_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='intended_use',
            field=models.TextField(blank=True, help_text='What this model is for, which population it was validated on, and what it must NOT be used for. Shown to reviewers; a model without this cannot be assessed for whether it fits the patient in front of you.'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='model_file_sha256',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of the uploaded model file, computed on save. Identifies the exact artifact.', max_length=64),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='version',
            field=models.CharField(blank=True, default='1', help_text='Version of this model. Change it whenever the model file changes; past predictions keep the version they were made with.', max_length=50),
        ),
        migrations.AddField(
            model_name='modelprediction',
            name='model_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='modelprediction',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
