# Generated by Django 5.2.12 on 2026-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emergency_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Patients are auto-approved. Doctors, Data Scientists, and Hospital Admins require admin approval.'),
        ),
    ]
