# Generated by Django 5.2.12 on 2026-07-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patientprofile_encrypted_national_id_doctoraccesslog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='doctoraccesslog',
            new_name='accounts_do_patient_1d6430_idx',
            old_name='accounts_do_patient_b94c45_idx',
        ),
    ]
