# Generated by Django 5.2.12 on 2026-07-14 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_accounts_do_patient_b94c45_idx_accounts_do_patient_1d6430_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_card_enabled',
            field=models.BooleanField(default=True, help_text='Patient can disable to block all public access to their card'),
        ),
        migrations.CreateModel(
            name='EmergencyCardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(help_text='SHA-256 of visitor IP — never stores raw IP', max_length=64)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_views', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['profile', '-viewed_at'], name='accounts_em_profile_c63451_idx')],
            },
        ),
    ]
