# Generated by Django 5.2.12 on 2026-08-12 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_unique_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('ai_processing', 'AI analysis of my health data'), ('external_llm', 'Sending my health data to external AI providers'), ('document_processing', 'Automated reading of my uploaded documents'), ('data_sharing', 'Sharing my records with linked clinicians'), ('research', 'Use of anonymised data for research')], max_length=32)),
                ('version', models.CharField(help_text='Version of the consent text the user agreed to, e.g. "v1".', max_length=20)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked')], default='granted', max_length=10)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'status'], name='accounts_co_user_id_693b6e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'granted')), fields=('user', 'purpose'), name='unique_active_consent_per_user_purpose')],
            },
        ),
    ]
