# Generated by Django 5.2.12 on 2026-08-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdoctorrelationship',
            name='is_active',
        ),
        migrations.AddField(
            model_name='patientdoctorrelationship',
            name='decided_at',
            field=models.DateTimeField(blank=True, help_text='When the patient approved or revoked this link.', null=True),
        ),
        migrations.AddField(
            model_name='patientdoctorrelationship',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting patient approval'), ('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='pending', help_text='Only "active" grants the doctor access to records.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='patientdoctorrelationship',
            index=models.Index(fields=['patient', 'status'], name='accounts_pa_patient_97c76f_idx'),
        ),
    ]
