# Generated by Django 5.2.12 on 2026-08-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_patientdoctorrelationship_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_card_enabled',
            field=models.BooleanField(default=False, help_text='Opt-in. When True, the card is readable by anyone holding the token URL, with no login.'),
        ),
    ]
