# Generated by Django 5.2.12 on 2026-08-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_backfill_data_sharing_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdoctorrelationship',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting patient approval'), ('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='pending', help_text='"active" is necessary but NOT sufficient: the patient must also hold the DATA_SHARING consent, which is a master switch over every link. Ask authz.doctor_has_active_link, never this field alone.', max_length=10),
        ),
    ]
