# Generated by Django 5.2.12 on 2026-08-14 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_relationship_status_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, default='', max_length=200)),
                ('action', models.CharField(choices=[('user_approved', 'User approved'), ('user_rejected', 'User rejected and deleted'), ('model_approved', 'AI model approved'), ('model_activated', 'AI model activated'), ('model_rejected', 'AI model rejected'), ('escalation_denied', 'Authority change refused')], db_index=True, max_length=32)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_label', models.CharField(blank=True, default='', help_text='Human-readable identifier of the target at the time of the action. Never clinical content.', max_length=200)),
                ('authority', models.CharField(blank=True, default='', max_length=64)),
                ('success', models.BooleanField(default=True, help_text='False for refused attempts, which are the ones worth reading.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Scalars only — counts, identifiers, reasons.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='The administrator who acted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='accounts_ad_action_22f80e_idx')],
            },
        ),
    ]
