# Generated by Django 5.2.12 on 2026-08-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_admin_audit_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditevent',
            name='action',
            field=models.CharField(choices=[('user_approved', 'User approved'), ('user_rejected', 'User rejected and deleted'), ('model_approved', 'AI model approved'), ('model_activated', 'AI model activated'), ('model_rejected', 'AI model rejected'), ('escalation_denied', 'Authority change refused'), ('value_corrected', 'Clinical value corrected')], db_index=True, max_length=32),
        ),
    ]
