# Generated by Django 5.2.12 on 2026-08-14 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_adminauditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditevent',
            name='action',
            field=models.CharField(choices=[('user_approved', 'User approved'), ('user_rejected', 'User rejected and deleted'), ('model_approved', 'AI model approved'), ('model_activated', 'AI model activated'), ('model_rejected', 'AI model rejected'), ('escalation_denied', 'Authority change refused'), ('value_corrected', 'Clinical value corrected'), ('share_revoked', 'Sharing grant revoked by admin'), ('share_denied', 'Sharing action refused')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='SharingGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_records', models.BooleanField(default=False, help_text='Medical records, lab values and the files behind them.')),
                ('can_view_alerts', models.BooleanField(default=False, help_text='That an alert exists and how severe — not its values.')),
                ('can_view_appointments', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='After this instant the grant gives nothing, without anyone having to revoke it.', null=True)),
                ('data_cutoff', models.DateTimeField(blank=True, help_text='When set, only records uploaded before this instant are visible.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=200)),
                ('patient', models.ForeignKey(help_text='The person whose data is shared. The only authority that can create this row.', on_delete=django.db.models.deletion.CASCADE, related_name='shares_granted', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, help_text='The patient, or an administrator acting on a report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='accounts_sh_recipie_4950d3_idx'), models.Index(fields=['patient', 'status'], name='accounts_sh_patient_7660a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('patient', 'recipient'), name='unique_sharing_grant_per_pair'), models.CheckConstraint(condition=models.Q(('patient', models.F('recipient')), _negated=True), name='sharing_grant_not_self')],
            },
        ),
    ]
