# Generated by Django 5.2.12 on 2026-04-02 23:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('diagnosis', 'Diagnosis'), ('vaccination', 'Vaccination'), ('imaging', 'Imaging Report'), ('wearable', 'Wearable Data'), ('discharge', 'Discharge Summary'), ('other', 'Other')], default='other', max_length=20)),
                ('source', models.CharField(choices=[('kanta_xml', 'Kanta XML Import'), ('wearable_csv', 'Wearable CSV Import'), ('manual_upload', 'Manual Upload')], default='manual_upload', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_records/%Y/%m/')),
                ('raw_text', models.TextField(blank=True, help_text='Extracted text from file')),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='Structured parsed data')),
                ('notes', models.TextField(blank=True)),
                ('record_date', models.DateField(blank=True, help_text='Date the record was created/measured', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged by AI as having abnormal values')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedLabValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('measured_at', models.DateTimeField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_values', to='medical_records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='WearableDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('heart_rate', 'Heart Rate (bpm)'), ('steps', 'Steps'), ('sleep', 'Sleep (hours)'), ('calories', 'Calories Burned'), ('blood_oxygen', 'Blood Oxygen (%)'), ('weight', 'Weight (kg)'), ('temperature', 'Body Temperature'), ('other', 'Other')], default='other', max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_points', to='medical_records.medicalrecord')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
