# Generated by Django 5.2.12 on 2026-07-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedlabvalue',
            name='canonical_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedlabvalue',
            name='original_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='source',
            field=models.CharField(choices=[('kanta_xml', 'Kanta XML Import'), ('wearable_csv', 'Wearable Import'), ('manual_upload', 'Manual Upload')], default='manual_upload', max_length=20),
        ),
    ]
