# Generated by Django 5.2.12 on 2026-07-14 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_parsedlabvalue_unit_known'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', '-record_date'], name='medical_rec_patient_c5092c_idx'),
        ),
    ]
