# Generated by Django 5.2.12 on 2026-08-13 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_medicalrecord_medical_rec_patient_c5092c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 of the ingested content. Empty when unknown (pre-existing rows); such rows are exempt from de-duplication.', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='medicalrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('content_hash', ''), _negated=True), fields=('patient', 'content_hash'), name='unique_record_content_per_patient'),
        ),
    ]
