# Generated by Django 5.2.12 on 2026-08-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_medicalrecord_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='indexed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when RAG indexing last succeeded. NULL means this record is not searchable by the assistant.', null=True),
        ),
    ]
