# Generated by Django 5.2.12 on 2026-08-14 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0007_lab_value_patient_and_ordering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabValueCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('canonical_value', models.FloatField(blank=True, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=50)),
                ('unit_known', models.BooleanField(default=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('reason', models.TextField(help_text='Why the extracted value was wrong. Recorded verbatim.')),
                ('source', models.CharField(blank=True, default='', help_text='What the correction was based on — e.g. "re-read of the source PDF", "laboratory confirmation".', max_length=200)),
                ('actor_label', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_value_corrections', to=settings.AUTH_USER_MODEL)),
                ('original', models.ForeignKey(help_text='The extracted value this supersedes. Never modified.', on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='medical_records.parsedlabvalue')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['original', '-created_at'], name='medical_rec_origina_3cae1b_idx')],
            },
        ),
    ]
