# Generated by Django 5.2.12 on 2026-08-14 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0008_labvaluecorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asserted_on', models.DateField(blank=True, help_text='The document date this assertion belongs to. NULL when the document carried no date; such statements cannot be ordered and are reported as undated rather than assumed recent.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, default='', help_text='ICD or local code when the document gave one.', max_length=32)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=16)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.medicalrecord')),
            ],
            options={
                'ordering': ['-asserted_on', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['patient', 'description', '-asserted_on'], name='medical_rec_patient_d39f10_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicationStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asserted_on', models.DateField(blank=True, help_text='The document date this assertion belongs to. NULL when the document carried no date; such statements cannot be ordered and are reported as undated rather than assumed recent.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('dose', models.CharField(blank=True, default='', max_length=100)),
                ('frequency', models.CharField(blank=True, default='', max_length=100)),
                ('route', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Being taken'), ('discontinued', 'Stopped')], default='active', max_length=16)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.medicalrecord')),
            ],
            options={
                'ordering': ['-asserted_on', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['patient', 'name', '-asserted_on'], name='medical_rec_patient_07c918_idx')],
            },
        ),
    ]
