# Generated by Django 5.2.12 on 2026-08-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0009_clinical_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionstatement',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
