# Generated by Django 5.2.12 on 2026-08-15 15:07

from django.db import migrations, models


def carry_forward_existing_state(apps, schema_editor):
    """
    Rows that already have an indexed_at start as INDEXED, not PENDING.

    The new column defaults to PENDING, which for an existing deployment would
    mean every record ever indexed becomes claimable again and the next sweep
    re-embeds the entire corpus — real money, real quota, and a long window
    where the assistant is degraded.

    The old timestamp was not a reliable success signal (that is the defect this
    migration accompanies), so this is not perfect knowledge. But treating a
    previously-indexed record as indexed is closer to the truth than treating it
    as never processed, and anything genuinely stale is corrected the next time
    the record is saved or a reindex sweep runs.
    """
    MedicalRecord = apps.get_model('medical_records', 'MedicalRecord')
    MedicalRecord.objects.filter(indexed_at__isnull=False).update(
        index_status='indexed')


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0010_condition_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='index_attempts',
            field=models.PositiveIntegerField(default=0, help_text='How many times indexing has been claimed for this record.'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='index_error',
            field=models.CharField(blank=True, default='', help_text='Why the last attempt did not succeed. Error TYPE and a short reason only — never provider output, which can quote the document it was given.', max_length=300),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='index_started_at',
            field=models.DateTimeField(blank=True, help_text='When the current or last indexing attempt was claimed. Used to find work abandoned by a worker that died mid-run.', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='index_status',
            field=models.CharField(choices=[('pending', 'Waiting to be indexed'), ('indexing', 'Being indexed now'), ('indexed', 'Searchable'), ('failed', 'Indexing failed'), ('blocked', 'Not permitted to index')], db_index=True, default='pending', help_text='Where this record is in the indexing lifecycle. Only "indexed" means the assistant can find it.', max_length=16),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='indexed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when RAG indexing last SUCCEEDED, and only then. NULL means this record is not searchable by the assistant.', null=True),
        ),
        # Reverse is a no-op: going back drops the column this sets.
        migrations.RunPython(carry_forward_existing_state,
                             migrations.RunPython.noop),
    ]
