# Generated by Django 5.2.12 on 2026-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0011_index_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='index_claim',
            field=models.UUIDField(blank=True, help_text='Token identifying the current indexing attempt. Only the holder may record its outcome.', null=True),
        ),
    ]
