# Generated by Django 5.2.12 on 2026-05-25 11:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name, e.g. "Acne Treatment Course"', max_length=200)),
                ('condition', models.CharField(help_text='Medical condition being treated', max_length=200)),
                ('specialty', models.CharField(choices=[('dermatology', 'Dermatology'), ('cardiology', 'Cardiology'), ('endocrinology', 'Endocrinology'), ('neurology', 'Neurology'), ('gastro', 'Gastroenterology'), ('orthopedics', 'Orthopedics'), ('pulmonology', 'Pulmonology'), ('rheumatology', 'Rheumatology'), ('oncology', 'Oncology'), ('psychiatry', 'Psychiatry'), ('general', 'General / Family'), ('other', 'Other')], default='other', max_length=30)),
                ('doctor_name', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, help_text='Estimated end of treatment (optional)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('medications', models.TextField(blank=True, help_text='Medications used in this course (free text)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biomarker_name', models.CharField(help_text='e.g. "ALT (Liver)", "Triglycerides"', max_length=100)),
                ('frequency_days', models.PositiveIntegerField(help_text='How often to test this (in days), e.g. 30')),
                ('last_checked', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='Why this is being monitored', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='treatments.treatmentcourse')),
            ],
            options={
                'ordering': ['biomarker_name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=200)),
                ('milestone_type', models.CharField(choices=[('visit', 'Doctor Visit'), ('lab_test', 'Lab Test'), ('med_change', 'Medication Change'), ('symptom', 'Symptom / Side Effect'), ('photo', 'Progress Photo Note'), ('other', 'Other')], default='other', max_length=20)),
                ('outcome', models.CharField(choices=[('improved', 'Improved'), ('stable', 'Stable'), ('worsened', 'Worsened'), ('pending', 'Pending / Unknown')], default='pending', max_length=15)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='treatments.treatmentcourse')),
                ('linked_record', models.ForeignKey(blank=True, help_text='Link to an uploaded lab/record if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_milestones', to='medical_records.medicalrecord')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
