# Generated by Django 5.2.12 on 2026-05-25 23:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('symptom_name', models.CharField(help_text='e.g. "Redness", "Pain", "Itch"', max_length=100)),
                ('severity', models.PositiveSmallIntegerField(help_text='1 (minimal) — 10 (severe)')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to='treatments.treatmentcourse')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='treatment_photos/%Y/%m/')),
                ('date', models.DateField(default=datetime.date.today)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('body_area', models.CharField(blank=True, help_text='e.g. "Face", "Left arm", "Back"', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='treatments.treatmentcourse')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
