# Generated by Django 5.2.12 on 2026-08-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretask',
            name='medication_statement',
        ),
    ]
