# Generated by Django 5.2.12 on 2026-04-14 11:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_assistant', '0002_medicaldocument_medicalchunk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicalchunk',
            new_name='rag_assista_patient_1cfe63_idx',
            old_name='ragchunk_patient_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalchunk',
            new_name='rag_assista_documen_f8759b_idx',
            old_name='ragchunk_doc_idx',
        ),
        migrations.RenameIndex(
            model_name='medicaldocument',
            new_name='rag_assista_patient_8bfed0_idx',
            old_name='ragdoc_patient_type_idx',
        ),
        migrations.RenameIndex(
            model_name='medicaldocument',
            new_name='rag_assista_patient_9bbb65_idx',
            old_name='ragdoc_patient_date_idx',
        ),
        migrations.AddField(
            model_name='querylog',
            name='llm_provider',
            field=models.CharField(blank=True, default='', help_text='Which LLM produced the response: gemini, anthropic, openai, fallback', max_length=20),
        ),
        migrations.AddField(
            model_name='querylog',
            name='retrieved_chunks_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of chunks passed to the LLM as context', null=True),
        ),
        migrations.AlterField(
            model_name='medicalchunk',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
