# Generated by Django 5.2.12 on 2026-05-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_assistant', '0006_querylog_chart_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='generalknowledgechunk',
            new_name='rag_assista_topic_fa3ae7_idx',
            old_name='rag_gkc_topic_idx',
        ),
        migrations.RenameIndex(
            model_name='generalknowledgechunk',
            new_name='rag_assista_source__3b2610_idx',
            old_name='rag_gkc_source_idx',
        ),
    ]
