# Generated by Django 5.2.12 on 2026-07-14 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_assistant', '0007_rename_rag_gkc_topic_idx_rag_assista_topic_fa3ae7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['patient', '-updated_at'], name='rag_assista_patient_24f418_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['session', 'created_at'], name='rag_assista_session_7b4eaf_idx'),
        ),
    ]
