# Generated by Django 5.2.12 on 2026-08-12 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_assistant', '0008_chatsession_rag_assista_patient_24f418_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generalknowledgechunk',
            name='embedded_at',
            field=models.DateTimeField(blank=True, help_text='When `embedding` was generated (not when the row was created).', null=True),
        ),
        migrations.AddField(
            model_name='generalknowledgechunk',
            name='embedding_dimensions',
            field=models.PositiveIntegerField(blank=True, help_text='Length of the stored vector, recorded at write time.', null=True),
        ),
        migrations.AddField(
            model_name='generalknowledgechunk',
            name='embedding_model',
            field=models.CharField(blank=True, default='', help_text="Model that produced `embedding`, e.g. 'models/gemini-embedding-001'. Empty means the vector predates provenance tracking.", max_length=100),
        ),
        migrations.AddField(
            model_name='generalknowledgechunk',
            name='embedding_model_version',
            field=models.CharField(blank=True, default='', help_text='Provider-reported model version, when the API exposes one. Gemini currently does not.', max_length=50),
        ),
        migrations.AddField(
            model_name='medicalchunk',
            name='embedded_at',
            field=models.DateTimeField(blank=True, help_text='When `embedding` was generated (not when the row was created).', null=True),
        ),
        migrations.AddField(
            model_name='medicalchunk',
            name='embedding_dimensions',
            field=models.PositiveIntegerField(blank=True, help_text='Length of the stored vector, recorded at write time.', null=True),
        ),
        migrations.AddField(
            model_name='medicalchunk',
            name='embedding_model',
            field=models.CharField(blank=True, default='', help_text="Model that produced `embedding`, e.g. 'models/gemini-embedding-001'. Empty means the vector predates provenance tracking.", max_length=100),
        ),
        migrations.AddField(
            model_name='medicalchunk',
            name='embedding_model_version',
            field=models.CharField(blank=True, default='', help_text='Provider-reported model version, when the API exposes one. Gemini currently does not.', max_length=50),
        ),
        migrations.AddIndex(
            model_name='generalknowledgechunk',
            index=models.Index(fields=['embedding_model'], name='rag_assista_embeddi_efeb1a_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalchunk',
            index=models.Index(fields=['embedding_model'], name='rag_assista_embeddi_6895ef_idx'),
        ),
    ]
