# Generated by Django 5.2.12 on 2026-08-13 10:33

from django.db import migrations, models


def _backfill_status(apps, schema_editor):
    """
    Existing rows already carry the truth in `embedding`; the new status column
    must agree with it. Without this, every previously-embedded chunk would read
    'pending' and the recovery tooling would report a healthy index as entirely
    unindexed.

    Rows with no vector are deliberately left 'pending' rather than 'failed':
    we cannot know retrospectively whether they failed, were blocked by consent,
    or were never attempted. 'pending' is the honest, retryable state.
    """
    for model_name in ('MedicalChunk', 'GeneralKnowledgeChunk'):
        model = apps.get_model('rag_assistant', model_name)
        model.objects.filter(embedding__isnull=False).update(embedding_status='embedded')


def _noop_reverse(apps, schema_editor):
    """Reversing this migration drops the columns; there is nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('rag_assistant', '0009_generalknowledgechunk_embedded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalknowledgechunk',
            name='embedding_attempted_at',
            field=models.DateTimeField(blank=True, help_text='When embedding was last attempted, successful or not.', null=True),
        ),
        migrations.AddField(
            model_name='generalknowledgechunk',
            name='embedding_attempts',
            field=models.PositiveIntegerField(default=0, help_text='How many times embedding has been attempted for this row.'),
        ),
        migrations.AddField(
            model_name='generalknowledgechunk',
            name='embedding_error',
            field=models.CharField(blank=True, default='', help_text='Short reason for the last failure. Empty when not failed.', max_length=300),
        ),
        migrations.AddField(
            model_name='generalknowledgechunk',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('embedded', 'Embedded'), ('failed', 'Failed'), ('blocked', 'Blocked')], db_index=True, default='pending', help_text='Explicit indexing state. NULL embedding alone cannot distinguish "not tried yet" from "failed permanently".', max_length=10),
        ),
        migrations.AddField(
            model_name='medicalchunk',
            name='embedding_attempted_at',
            field=models.DateTimeField(blank=True, help_text='When embedding was last attempted, successful or not.', null=True),
        ),
        migrations.AddField(
            model_name='medicalchunk',
            name='embedding_attempts',
            field=models.PositiveIntegerField(default=0, help_text='How many times embedding has been attempted for this row.'),
        ),
        migrations.AddField(
            model_name='medicalchunk',
            name='embedding_error',
            field=models.CharField(blank=True, default='', help_text='Short reason for the last failure. Empty when not failed.', max_length=300),
        ),
        migrations.AddField(
            model_name='medicalchunk',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('embedded', 'Embedded'), ('failed', 'Failed'), ('blocked', 'Blocked')], db_index=True, default='pending', help_text='Explicit indexing state. NULL embedding alone cannot distinguish "not tried yet" from "failed permanently".', max_length=10),
        ),
        migrations.RunPython(_backfill_status, _noop_reverse),
    ]
