# Generated by Django 5.2.12 on 2026-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='input_type',
            field=models.CharField(choices=[('tabular', 'Tabular (manual form)'), ('image', 'Image (JPG/PNG/DICOM)'), ('eeg_csv', 'EEG / Signal (CSV)'), ('parquet', 'Tabular file (Parquet/CSV upload)'), ('audio', 'Audio file'), ('file', 'Generic file')], default='tabular', help_text='How the patient provides input data', max_length=20),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='interpretation_guide',
            field=models.TextField(blank=True, help_text='Plain-text guide for AI interpretation. Describe the disease/condition, what the risk levels mean, and what actions the patient should take. Gemini will use this to generate a personalised explanation after each prediction.'),
        ),
        migrations.AddField(
            model_name='modelprediction',
            name='input_file',
            field=models.FileField(blank=True, help_text='Uploaded file used as input (image, EEG, etc.)', null=True, upload_to='prediction_inputs/'),
        ),
        migrations.AddField(
            model_name='modelprediction',
            name='interpretation',
            field=models.TextField(blank=True, help_text='AI-generated patient-friendly interpretation of the result'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='input_schema',
            field=models.JSONField(default=dict, help_text='JSON definition of required input fields (for tabular input)'),
        ),
    ]
