# Generated by Django 5.2.12 on 2026-07-14 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_recreate_with_uuid_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'appointment_datetime'], name='appointment_patient_6bcbef_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_datetime', 'is_cancelled'], name='appointment_appoint_dc0db8_idx'),
        ),
    ]
