# Generated by Django 5.2.12 on 2026-08-15 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_care_monitoring'),
        ('notifications', '0003_notification_notificatio_user_id_427e4b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('care_signal', 'Care monitoring signal'), ('task_reminder', 'Task reminder'), ('appointment', 'Appointment reminder')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'For information'), ('attention', 'Worth a look'), ('urgent', 'Needs attention now')], default='attention', max_length=16)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=200)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='care.monitoringsignal')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events_about', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed'), ('unavailable', 'Channel not available here')], default='pending', max_length=16)),
                ('detail', models.CharField(blank=True, default='', max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notificationevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['subject', '-created_at'], name='notificatio_subject_5d9608_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['dedupe_key', '-created_at'], name='notificatio_dedupe__ec6150_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_93a391_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'channel'], name='notificatio_status_1f3a81_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'recipient', 'channel'), name='unique_delivery_per_event_recipient_channel'),
        ),
    ]
